[colors-dark]
# Default foreground/background
foreground=e2e3d8
background=12140e

# Regular colors
regular0=12140e         # Black
regular1=ffb4ab               # Red
regular2=b1d18a             # Green
regular3=a0d0cb            # Yellow
regular4=bfcbad           # Blue
regular5=4c662b     # Magenta
regular6=354e16   # Cyan
regular7=c5c8ba  # White

# Bright colors
bright0=33362e # Bright Black
bright1=93000a           # Bright Red
bright2=4c662b           # Bright Green
bright3=404a33       # Bright Yellow
bright4=b1d18a                   # Bright Blue
bright5=1f4e4b        # Bright Magenta
bright6=a0d0cb                  # Bright Cyan
bright7=e2e3d8                # Bright White
