[colors-dark]
# Default foreground/background
foreground=e7e0e8
background=141218

# Regular colors
regular0=141218         # Black
regular1=ffb4ab               # Red
regular2=d1bcfd             # Green
regular3=f0b8c6            # Yellow
regular4=ccc2db           # Blue
regular5=67558e     # Magenta
regular6=4e3d75   # Cyan
regular7=cbc4cf  # White

# Bright colors
bright0=36343a # Bright Black
bright1=93000a           # Bright Red
bright2=67558e           # Bright Green
bright3=4a4358       # Bright Yellow
bright4=d1bcfd                   # Bright Blue
bright5=643b47        # Bright Magenta
bright6=f0b8c6                  # Bright Cyan
bright7=e7e0e8                # Bright White
